GET http://34.232.6.92/test

###

POST http://34.232.6.92/register
Content-Type: application/json

{
    "username": "Kyle",
    "password": "1234",
    "email": "test@test.com"
}

###

POST http://34.232.6.92/login
Content-Type: application/json

{
    "username": "Kyle",
    "password": "1234"
}