POST http://localhost/register
Content-Type: application/json

{
    "username": "qq",
    "password": "qq",
    "email": "test@test.com"
}

###

POST http://localhost/login
Content-Type: application/json

{
    "username": "qq",
    "password": "qq"
}